id: P17288177
initial_creation_type: input
source_metadata:
  title: Shakya Shri Series
  language: bo
  description: 'Texts by the great yogi Tokden Shakya Shri (rtogs ldan shākya shrī,
    1853–1919):'
  volume:
    534e3a31306b49e3a7ba88c7dc626174:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Guru Yoga
    1de52bb7eb7d4f91b4126bc352066012:
      title: Supplication to Lord Mila Shepa Dorje
      parent: Prayers
    41327711252f49f78a18155cd37bdc5e:
      title: 'The Shower of Blessings: A Prayer'
      parent: Prayers
created_at: '2022-03-01T01:32:11.871724'
last_modified_at: '2022-03-01T01:32:11.871726'
statistics:
  total_words: 1964
  total_non_words: 186
quality:
  non_words_ratio: 0.09
